#%RAML 1.0
title: American Flights API
version: 1.0

/flights:
  get:
    queryParameters: 
      code:
  post:
    body: 
      application/json:
        example: 
        {"code": "GQ574","price": 399, "departureDate":016/12/20",
           "origin": "ORD","destination": "SFO","emptySeats": 200,
           "plane":
           {"type": "Boeing 747", "totalSeats": 400}
        }
/{ID}:
  get:
    responses: 
      200:
        body:
          application/json:
            example: 
            {"message": "Flight added (but not really)"}
            
    
  